# Generated by Django 4.0.3 on 2022-03-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='content',
        ),
    ]
